### ISSUE TITLE
POST https://apiwhaticket/auth/refresh_token 401 (Unauthorized)

### ISSUE THREAD

**Issue by hugomza2003** [ticketz-oss/ticketz-docker-acme#1]
Good day, install (curl -sSL get.ticke.tz | sudo bash -s backend.example.com frontend.example.com [name@example.com](mailto:name@example.com)) and I get a refresh token error, does anyone have the same problem.
The 2 subdomains are from noip.com pointing to my server with dns record A.
thank you

error: POST https://apiwhaticket/auth/refresh_token 401 (Unauthorized)

Ubuntu 22.04
chrome

**Comment by allgood** [comment]
currently Ticketz uses only one hostname and should have no problem on using it from noip.
